### ISSUE TITLE
Not compiling for Feather M0+

### ISSUE THREAD

**Issue by RadJaz** [adafruit/Adafruit_SHARP_Memory_Display#5]
When trying to compile for the Feather M0+ using the Arduino IDE, I get an error message:

`Warning: platform.txt from core 'Adafruit SAMD Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
/home/jaz/Arduino/libraries/Adafruit_SHARP_Memory_Display/Adafruit_SharpMem.cpp: In constructor 'Adafruit_SharpMem::Adafruit_SharpMem(uint8_t, uint8_t, uint8_t)':
/home/jaz/Arduino/libraries/Adafruit_SHARP_Memory_Display/Adafruit_SharpMem.cpp:64:15: error: cannot convert 'volatile uint32_t* {aka volatile long unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
   clkport     = portOutputRegister(digitalPinToPort(_clk));
               ^
/home/jaz/Arduino/libraries/Adafruit_SHARP_Memory_Display/Adafruit_SharpMem.cpp:66:15: error: cannot convert 'volatile uint32_t* {aka volatile long unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
   dataport    = portOutputRegister(digitalPinToPort(_mosi));
               ^
exit status 1
Error compiling.
`

I'd assume these lines that are inducing the error are some AVR specific stuff. I'm not sure though because I've had this library compile on a Teensy 3.2.

**Comment by RadJaz** [comment]
Pull request #6 fixes this issue and #7 is a fork of that that also includes color depth functionality.

**Comment by dhiltonp** [comment]
I fixed a whitespace issue and reverted to the included swap defines.

At least with Arduino 1.6.9, the global "swap" define doesn't seem to exist.

**Comment by ladyada** [comment]
try now should be fixed! with latest commit!
